### ISSUE TITLE
to create a new Java class BaseModel to serve as the base persistent object for primary key, created and modified dates and other useful base model data. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#12]
# Mission to create a new Java class BaseModel to serve as the base persistent object for primary key, created and modified dates and other useful base model data. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java class BaseModel to serve as the base persistent object for primary key, created and modified dates and other useful base model data. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.base
- **The Java class name will be:** BaseModel
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/base/BaseModel.java
- **The Java class will extend:** BaseModelGen\<Object\>

```java
package io.serratus.api.enus.base;

import java.text.Normalizer;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.List;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.apache.commons.lang3.reflect.FieldUtils;
import io.serratus.api.enus.config.ConfigKeys;
import io.serratus.api.enus.request.SiteRequestEnUS;
import io.serratus.api.enus.wrap.Wrap;

/**
 * Indexed: true
 **/

public class BaseModel extends BaseModelGen<Object> {
}
```

## Create the init method for the siteRequest_ field inside the BaseModel class

Create an initialization method that starts with an underscore (_)siteRequest_ to define the  siteRequest_ field

Here is a suggestion on what the code might look like: 

```java
	protected void _siteRequest_(Wrap<SiteRequestEnUS> w) {}
```

## Create the init method for the pk field inside the BaseModel class

Create an initialization method that starts with an underscore (_)pk to define the  pk field

Here is a suggestion on what the code might look like: 

```java
	protected void _pk(Wrap<Long> w) {}
```

## Create the init method for the inheritPk field inside the BaseModel class

Create an initialization method that starts with an underscore (_)inheritPk to define the  inheritPk field

Here is a suggestion on what the code might look like: 

```java
	protected void _inheritPk(Wrap<String> w) {}
```

## Create the init method for the id field inside the BaseModel class

Create an initialization method that starts with an underscore (_)id to define the  id field

Here is a suggestion on what the code might look like: 

```java
	protected void _id(Wrap<String> w) {
		if(pk != null)
			w.o(getClass().getSimpleName() + "_" + pk.toString());
	}
```

## Create the init method for the created field inside the BaseModel class

Create an initialization method that starts with an underscore (_)created to define the  created field

Here is a suggestion on what the code might look like: 

```java
	protected void _created(Wrap<ZonedDateTime> w) {}
```

## Create the init method for the modified field inside the BaseModel class

Create an initialization method that starts with an underscore (_)modified to define the  modified field

Here is a suggestion on what the code might look like: 

```java
	protected void _modified(Wrap<ZonedDateTime> w) {
		w.o(ZonedDateTime.now(ZoneId.of(siteRequest_.getConfig().getString(ConfigKeys.SITE_ZONE))));
	}
```

## Create the init method for the archived field inside the BaseModel class

Create an initialization method that starts with an underscore (_)archived to define the  archived field

Here is a suggestion on what the code might look like: 

```java
	protected void _archived(Wrap<Boolean> w) {
		w.o(false);
	}
```

## Create the init method for the deleted field inside the BaseModel class

Create an initialization method that starts with an underscore (_)deleted to define the  deleted field

Here is a suggestion on what the code might look like: 

```java
	protected void _deleted(Wrap<Boolean> w) {
		w.o(false);
	}
```

## Create the init method for the classCanonicalName field inside the BaseModel class

Create an initialization method that starts with an underscore (_)classCanonicalName to define the  classCanonicalName field

Here is a suggestion on what the code might look like: 

```java
	protected void _classCanonicalName(Wrap<String> w) {
		w.o(getClass().getCanonicalName());
	}
```

## Create the init method for the classSimpleName field inside the BaseModel class

Create an initialization method that starts with an underscore (_)classSimpleName to define the  classSimpleName field

Here is a suggestion on what the code might look like: 

```java
	protected void _classSimpleName(Wrap<String> w) {
		w.o(getClass().getSimpleName());
	}
```

## Create the init method for the sessionId field inside the BaseModel class

Create an initialization method that starts with an underscore (_)sessionId to define the  sessionId field

Here is a suggestion on what the code might look like: 

```java
	protected void _sessionId(Wrap<String> w) {
	}
```

## Create the init method for the userKey field inside the BaseModel class

Create an initialization method that starts with an underscore (_)userKey to define the  userKey field

Here is a suggestion on what the code might look like: 

```java
	protected void _userKey(Wrap<Long> c) {
	}
```

## Create the init method for the saves field inside the BaseModel class

Create an initialization method that starts with an underscore (_)saves to define the  saves field

Here is a suggestion on what the code might look like: 

```java
protected void _saves(List<String> l) {
	}
```

## Create the init method for the objectTitle field inside the BaseModel class

Create an initialization method that starts with an underscore (_)objectTitle to define the  objectTitle field

Here is a suggestion on what the code might look like: 

```java
	protected void _objectTitle(Wrap<String> w) {
		w.o(toString());
	}
```

## Create the init method for the objectId field inside the BaseModel class

Create an initialization method that starts with an underscore (_)objectId to define the  objectId field

Here is a suggestion on what the code might look like: 

```java
	protected void _objectId(Wrap<String> w) {
		if(objectTitle != null) {
			w.o(toId(objectTitle));
		}
		else if(pk != null){
			w.o(pk.toString());
		}
	}
```

## Create the toId method inside the BaseModel class

```java
	public String toId(String s) {
		if(s != null) {
			s = Normalizer.normalize(s, Normalizer.Form.NFD);
			s = StringUtils.lowerCase(s);
			s = StringUtils.trim(s);
			s = StringUtils.replacePattern(s, "\\s{1,}", "-");
			s = StringUtils.replacePattern(s, "[^\\w-]", "");
			s = StringUtils.replacePattern(s, "-{2,}", "-");
		}

		return s;
	}
```

## Create the init method for the objectNameVar field inside the BaseModel class

Create an initialization method that starts with an underscore (_)objectNameVar to define the  objectNameVar field

Here is a suggestion on what the code might look like: 

```java
	protected void _objectNameVar(Wrap<String> w) {
		if(objectId != null) {
			Class<?> cl = getClass();

			try {
				String o = toId(StringUtils.join(StringUtils.splitByCharacterTypeCamelCase((String)FieldUtils.getField(cl, cl.getSimpleName() + "_NameVar").get(this)), "-"));
				w.o(o);
			} catch (Exception e) {
				ExceptionUtils.rethrow(e);
			}
		}
	}
```

## Create the init method for the objectSuggest field inside the BaseModel class

Create an initialization method that starts with an underscore (_)objectSuggest to define the  objectSuggest field

Here is a suggestion on what the code might look like: 

```java
	protected void _objectSuggest(Wrap<String> w) { 
		w.o(toString());
	}
```

## Create the init method for the objectText field inside the BaseModel class

Create an initialization method that starts with an underscore (_)objectText to define the  objectText field

Here is a suggestion on what the code might look like: 

```java
	protected void _objectText(Wrap<String> w) { 
		w.o(toString());
	}
```

## Create the init method for the pageUrlId field inside the BaseModel class

Create an initialization method that starts with an underscore (_)pageUrlId to define the  pageUrlId field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageUrlId(Wrap<String> w) {
		if(objectId != null) {
			String o = siteRequest_.getConfig().getString(ConfigKeys.SITE_BASE_URL) + "/" + objectNameVar + "/" + objectId;
			w.o(o);
		}
	}
```

## Create the init method for the pageUrlPk field inside the BaseModel class

Create an initialization method that starts with an underscore (_)pageUrlPk to define the  pageUrlPk field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageUrlPk(Wrap<String> w) {
		if(pk != null) {
			String o = siteRequest_.getConfig().getString(ConfigKeys.SITE_BASE_URL) + "/" + objectNameVar + "/" + pk;
			w.o(o);
		}
	}
```

## Create the init method for the pageUrlApi field inside the BaseModel class

Create an initialization method that starts with an underscore (_)pageUrlApi to define the  pageUrlApi field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageUrlApi(Wrap<String> w) {
		if(pk != null) {
			String o = siteRequest_.getConfig().getString(ConfigKeys.SITE_BASE_URL) + "/api/" + objectNameVar + "/" + pk;
			w.o(o);
		}
	}
```

## Create the init method for the pageH1 field inside the BaseModel class

Create an initialization method that starts with an underscore (_)pageH1 to define the  pageH1 field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageH1(Wrap<String> w) {
		try {
			Class<?> cl = getClass();
			w.o((String)FieldUtils.getField(cl, cl.getSimpleName() + "_NameSingular").get(this) + ": " + objectTitle);
		} catch (Exception e) {
			ExceptionUtils.rethrow(e);
		}
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by manaswinidas** [comment]
Pull request link: https://github.com/team19hackathon2021/serratus-api/pull/8
