### ISSUE TITLE
to create a new Java class LocalTimeSerializer do convert a LocalTime to a String. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#17]
# Mission to create a new Java class LocalTimeSerializer do convert a LocalTime to a String. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java class LocalTimeSerializer do convert a LocalTime to a String. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.java
- **The Java class name will be:** LocalTimeSerializer
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/java/LocalTimeSerializer.java
- **The Java class will extend:** JsonSerializer\<LocalTime\>

```java
package io.serratus.api.enus.java;

import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;

/**
 **/

public class LocalTimeSerializer extends JsonSerializer<LocalTime> {
}
```

## Create the FORMATTimeDisplay field inside the LocalTimeSerializer class

```java
	public static DateTimeFormatter FORMATTimeDisplay = DateTimeFormatter.ofPattern("h:mm a", Locale.US);
```

## Create the serialize method inside the LocalTimeSerializer class

```java
	public void serialize(LocalTime o, JsonGenerator generator, SerializerProvider provider) {
		generator.writeString(FORMATTimeDisplay.format(o));
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by hect1995** [comment]
Assign to me
