### ISSUE TITLE
to create a new Java class Wrap to help with initialization of Java objects and pass back newly initialized class objects or null. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#20]
# Mission to create a new Java class Wrap to help with initialization of Java objects and pass back newly initialized class objects or null. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java class Wrap to help with initialization of Java objects and pass back newly initialized class objects or null. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.wrap
- **The Java class name will be:** Wrap
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/wrap/Wrap.java

```java
package io.serratus.api.enus.wrap;

import java.io.Serializable;
import java.util.ArrayList;

/**
 **/

public class Wrap<DEV> {
}
```

## Create the var field inside the Wrap class

```java
	public String var;
```

## Create the var method inside the Wrap class

```java
	public Wrap<DEV> var(String o) {
		var = o;
		return this;
	}
```

## Create the o field inside the Wrap class

```java
	public DEV o;
```

## Create the o method inside the Wrap class

```java
	public Wrap<DEV> o(DEV o) {
		this.o = o;
		return this;
	}
```

## Create the alreadyInitialized field inside the Wrap class

```java
	public Boolean alreadyInitialized = false;
```

## Create the alreadyInitialized method inside the Wrap class

```java
	public Wrap<DEV> alreadyInitialized(Boolean o) {
		alreadyInitialized = o;
		return this;
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by saifabusaleh** [comment]
I take this
