### ISSUE TITLE
to create a new Java class to store information about a given API request to use in building the responses to API and UI requests. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#27]
# Mission to create a new Java class to store information about a given API request to use in building the responses to API and UI requests. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java class to store information about a given API request to use in building the responses to API and UI requests. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.request
- **The Java class name will be:** SiteRequestEnUS
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/request/SiteRequestEnUS.java
- **The Java class will extend:** SiteRequestEnUSGen\<Object\>

```java
package io.serratus.api.enus.request;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Stack;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.apache.commons.lang3.StringUtils;
import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.common.SolrDocument;
import io.serratus.api.enus.request.api.ApiRequest;
import io.serratus.api.enus.wrap.Wrap;
import io.serratus.api.enus.writer.AllWriter;
import io.vertx.core.MultiMap;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.auth.User;
import io.vertx.ext.web.api.service.ServiceRequest;
import io.vertx.ext.web.client.WebClient;
import io.vertx.sqlclient.SqlConnection;

/**
 **/

public class SiteRequestEnUS extends SiteRequestEnUSGen<Object> {
}
```

## Create the PATTERN_SESSION field inside the SiteRequestEnUS class

```java
	private static final Pattern PATTERN_SESSION = Pattern.compile(".*vertx-web.session=(\\w+).*");
```

## Create the init method for the config field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)config to define the  config field

Here is a suggestion on what the code might look like: 

```java
	protected void _config(Wrap<JsonObject> c) {
	}
```

## Create the init method for the siteRequest_ field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)siteRequest_ to define the  siteRequest_ field

Here is a suggestion on what the code might look like: 

```java
	protected void _siteRequest_(Wrap<SiteRequestEnUS> c) { 
		c.o(this);
	}
```

## Create the init method for the webClient field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)webClient to define the  webClient field

Here is a suggestion on what the code might look like: 

```java
	protected void _webClient(Wrap<WebClient> c) { 
	}
```

## Create the init method for the apiRequest_ field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)apiRequest_ to define the  apiRequest_ field

Here is a suggestion on what the code might look like: 

```java
	protected void _apiRequest_(Wrap<ApiRequest> c) { 
	}
```

## Create the init method for the jsonObject field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)jsonObject to define the  jsonObject field

Here is a suggestion on what the code might look like: 

```java
	protected void _jsonObject(Wrap<JsonObject> c) {
	}
```

## Create the init method for the solrQuery field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)solrQuery to define the  solrQuery field

Here is a suggestion on what the code might look like: 

```java
	protected void _solrQuery(Wrap<SolrQuery> c) {
	}
```

## Create the init method for the serviceRequest field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)serviceRequest to define the  serviceRequest field

Here is a suggestion on what the code might look like: 

```java
	protected void _serviceRequest(Wrap<ServiceRequest> c) {
	}
```

## Create the init method for the user field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)user to define the  user field

Here is a suggestion on what the code might look like: 

```java
	protected void _user(Wrap<User> c) {
	}
```

## Create the init method for the userId field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userId to define the  userId field

Here is a suggestion on what the code might look like: 

```java
	protected void _userId(Wrap<String> c) {
		if(user != null) {
			String o = user.attributes().getString("sub");
			c.o(o);
		}
	}
```

## Create the init method for the userKey field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userKey to define the  userKey field

Here is a suggestion on what the code might look like: 

```java
	protected void _userKey(Wrap<Long> c) {
	}
```

## Create the init method for the sessionId field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)sessionId to define the  sessionId field

Here is a suggestion on what the code might look like: 

```java
	protected void _sessionId(Wrap<String> c) {
		if(serviceRequest != null) {
			String cookie = serviceRequest.getHeaders().get("Cookie");
			if(StringUtils.isNotBlank(cookie)) {
				Matcher m = PATTERN_SESSION.matcher(cookie);
				if(m.matches()) {
					c.o(m.group(1));
				}
			}
		}
	}
```

## Create the init method for the sessionIdBefore field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)sessionIdBefore to define the  sessionIdBefore field

Here is a suggestion on what the code might look like: 

```java
	protected void _sessionIdBefore(Wrap<String> c) {
		if(serviceRequest != null) {
			c.o(serviceRequest.getParams().getJsonObject("cookie").getString("sessionIdBefore"));
		}
	}
```

## Create the init method for the userName field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userName to define the  userName field

Here is a suggestion on what the code might look like: 

```java
	protected void _userName(Wrap<String> c) {
		if(user != null) {
			String o = user.attributes().getJsonObject("accessToken").getString("preferred_username");
			c.o(o);
		}
	}
```

## Create the init method for the userLastName field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userLastName to define the  userLastName field

Here is a suggestion on what the code might look like: 

```java
	protected void _userLastName(Wrap<String> c) {
		if(user != null) {
			String o = user.attributes().getJsonObject("accessToken").getString("family_name");
			c.o(o);
		}
	}
```

## Create the init method for the userFirstName field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userFirstName to define the  userFirstName field

Here is a suggestion on what the code might look like: 

```java
	protected void _userFirstName(Wrap<String> c) { 
		if(user != null) {
			String o = user.attributes().getJsonObject("accessToken").getString("given_name");
			c.o(o);
		}
	}
```

## Create the init method for the userFullName field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userFullName to define the  userFullName field

Here is a suggestion on what the code might look like: 

```java
	protected void _userFullName(Wrap<String> c) {
		if(user != null) {
			String o = user.attributes().getJsonObject("accessToken").getString("name");
			c.o(o);
		}
	}
```

## Create the init method for the userEmail field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userEmail to define the  userEmail field

Here is a suggestion on what the code might look like: 

```java
	protected void _userEmail(Wrap<String> c) {
		if(user != null) {
			String o = user.attributes().getJsonObject("accessToken").getString("email");
			c.o(o);
		}
	}
```

## Create the init method for the userRealmRoles field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userRealmRoles to define the  userRealmRoles field

Here is a suggestion on what the code might look like: 

```java
protected void _userRealmRoles(List<String> o) {
		JsonArray roles = Optional.ofNullable(user).map(user -> user.attributes()).map(attributes -> attributes.getJsonObject("accessToken")).map(o1 -> o1.getJsonObject("realm_access")).map(o2 -> o2.getJsonArray("roles")).orElse(new JsonArray());
		roles.stream().forEach(r -> {
			addUserRealmRoles((String)r);
		});
	}
```

## Create the init method for the userResource field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userResource to define the  userResource field

Here is a suggestion on what the code might look like: 

```java
	protected void _userResource(Wrap<JsonObject> c) {
		String authResource = config.getString("authResource");
		JsonObject o = Optional.ofNullable(user).map(user -> user.attributes()).map(p -> p.getJsonObject("resource_access")).map(o1 -> o1.getJsonObject(authResource)).orElse(new JsonObject());
		c.o(o);
	}
```

## Create the init method for the userResourceRoles field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)userResourceRoles to define the  userResourceRoles field

Here is a suggestion on what the code might look like: 

```java
protected void _userResourceRoles(List<String> o) {
		JsonArray roles = Optional.ofNullable(userResource).map(o2 -> o2.getJsonArray("roles")).orElse(new JsonArray());
		roles.stream().forEach(r -> {
			addUserResourceRoles((String)r);
		});
	}
```

## Create the init method for the solrDocument field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)solrDocument to define the  solrDocument field

Here is a suggestion on what the code might look like: 

```java
	protected void _solrDocument(Wrap<SolrDocument> c) {  
	}
```

## Create the init method for the pageAdmin field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)pageAdmin to define the  pageAdmin field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageAdmin(Wrap<Boolean> c) { 
		c.o(false);
	}
```

## Create the init method for the requestPk field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)requestPk to define the  requestPk field

Here is a suggestion on what the code might look like: 

```java
	protected void _requestPk(Wrap<Long> c) {
		if(serviceRequest != null)
			c.o(serviceRequest.getParams().getLong("pk"));
	}
```

## Create the init method for the requestUri field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)requestUri to define the  requestUri field

Here is a suggestion on what the code might look like: 

```java
	protected void _requestUri(Wrap<String> c) {
		c.o(Optional.ofNullable(serviceRequest).map(r -> r.getExtra()).map(extra -> extra.getString("uri")).orElse(null));
	}
```

## Create the init method for the requestMethod field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)requestMethod to define the  requestMethod field

Here is a suggestion on what the code might look like: 

```java
	protected void _requestMethod(Wrap<String> c) {
		c.o(Optional.ofNullable(serviceRequest).map(r -> r.getExtra()).map(extra -> extra.getString("method")).orElse(null));
	}
```

## Create the init method for the sqlConnection field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)sqlConnection to define the  sqlConnection field

Here is a suggestion on what the code might look like: 

```java
	protected void _sqlConnection(Wrap<SqlConnection> c) {
	}
```

## Create the init method for the requestHeaders field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)requestHeaders to define the  requestHeaders field

Here is a suggestion on what the code might look like: 

```java
	protected void _requestHeaders(Wrap<MultiMap> c) {
	}
```

## Create the init method for the requestVars field inside the SiteRequestEnUS class

Create an initialization method that starts with an underscore (_)requestVars to define the  requestVars field

Here is a suggestion on what the code might look like: 

```java
protected void _requestVars(Map<String, String> m) {
	}
```

## Create the copy method inside the SiteRequestEnUS class

```java
	public SiteRequestEnUS copy() {
		SiteRequestEnUS o = new SiteRequestEnUS();
		o.setJsonObject(jsonObject); // for copying the original data in the request
		o.setConfig(config); // for site configuration info
		o.setWebClient(webClient); // for performing searches
		o.setServiceRequest(serviceRequest);  // for info about the original request
		o.setUser(user); // The user principal
		o.setUserKey(userKey); // The user primary key
		o.setUserId(userId); // The user identifier in the authentication system
		o.setApiRequest_(apiRequest_); // The current API request information
		return o;
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by lautou** [comment]
working on it

**Comment by lautou** [comment]
done https://github.com/team19hackathon2021/serratus-api/pull/16
