### ISSUE TITLE
to create a new Java class to count the number of API requests are currently being made at the same time for fine tuning memory performance for bulk operations. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#29]
# Mission to create a new Java class to count the number of API requests are currently being made at the same time for fine tuning memory performance for bulk operations. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java class to count the number of API requests are currently being made at the same time for fine tuning memory performance for bulk operations. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.vertx
- **The Java class name will be:** ApiCounter
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/vertx/ApiCounter.java

```java
package io.serratus.api.enus.vertx;


/**
 **/

public class ApiCounter {
}
```

## Create the totalNum field inside the ApiCounter class

```java
	private Long totalNum;
```

## Create the getTotalNum method inside the ApiCounter class

```java
	public Long getTotalNum() {
		return totalNum;
	}
```

## Create the incrementTotalNum method inside the ApiCounter class

```java
	public void incrementTotalNum(Long num) {
		this.totalNum+=num;
	}
```

## Create the incrementTotalNum method inside the ApiCounter class

```java
	public void incrementTotalNum() {
		this.totalNum++;
	}
```

## Create the setTotalNum method inside the ApiCounter class

```java
	public void setTotalNum(Long totalNum) {
		this.totalNum = totalNum;
	}
```

## Create the queueNum field inside the ApiCounter class

```java
	private Long queueNum;
```

## Create the getQueueNum method inside the ApiCounter class

```java
	public Long getQueueNum() {
		return queueNum;
	}
```

## Create the incrementQueueNum method inside the ApiCounter class

```java
	public void incrementQueueNum(Long num) {
		this.queueNum+=num;
	}
```

## Create the incrementQueueNum method inside the ApiCounter class

```java
	public void incrementQueueNum() {
		this.queueNum++;
	}
```

## Create the decrementQueueNum method inside the ApiCounter class

```java
	public void decrementQueueNum() {
		this.queueNum--;
	}
```

## Create the setQueueNum method inside the ApiCounter class

```java
	public void setQueueNum(Long countNum) {
		this.queueNum = countNum;
	}
```

## Create the totalNumOld field inside the ApiCounter class

```java
	private Long totalNumOld;
```

## Create the getTotalNumOld method inside the ApiCounter class

```java
	public Long getTotalNumOld() {
		return totalNumOld;
	}
```

## Create the setTotalNumOld method inside the ApiCounter class

```java
	public void setTotalNumOld(Long totalNumOld) {
		this.totalNumOld = totalNumOld;
	}
```

## Create the queueNumOld field inside the ApiCounter class

```java
	private Long queueNumOld;
```

## Create the getQueueNumOld method inside the ApiCounter class

```java
	public Long getQueueNumOld() {
		return queueNumOld;
	}
```

## Create the setQueueNumOld method inside the ApiCounter class

```java
	public void setQueueNumOld(Long countNumOld) {
		this.queueNumOld = countNumOld;
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by pkesavap** [comment]
i can pick this up,

**Comment by pkesavap** [comment]
@lautou are you working on this, i already have code for it

**Comment by lautou** [comment]
yes i am into it

**Comment by lautou** [comment]
ok push your code

**Comment by pkesavap** [comment]
done
