### ISSUE TITLE
to create a new Java class to store a result from querying the search engine. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#30]
# Mission to create a new Java class to store a result from querying the search engine. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java class to store a result from querying the search engine. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.search
- **The Java class name will be:** SearchResult
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/search/SearchResult.java
- **The Java class will extend:** SearchResultGen\<Object\>

```java
package io.serratus.api.enus.search;

import org.apache.solr.common.SolrDocument;
import io.serratus.api.enus.request.SiteRequestEnUS;
import io.serratus.api.enus.wrap.Wrap;

/**
 **/

public class SearchResult extends SearchResultGen<Object> {
}
```

## Create the init method for the siteRequest_ field inside the SearchResult class

Create an initialization method that starts with an underscore (_)siteRequest_ to define the  siteRequest_ field

Here is a suggestion on what the code might look like: 

```java
	protected void _siteRequest_(Wrap<SiteRequestEnUS> c) {
	}
```

## Create the init method for the solrDocument field inside the SearchResult class

Create an initialization method that starts with an underscore (_)solrDocument to define the  solrDocument field

Here is a suggestion on what the code might look like: 

```java
	protected void _solrDocument(Wrap<SolrDocument> c) {
	}
```

## Create the init method for the resultIndex field inside the SearchResult class

Create an initialization method that starts with an underscore (_)resultIndex to define the  resultIndex field

Here is a suggestion on what the code might look like: 

```java
	protected void _resultIndex(Wrap<Long> c) {
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by pkesavap** [comment]
waiting for SearchResultGen to be implemented.
