### ISSUE TITLE
create a package-info.java class for Vert.x API code generation

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#44]
# Mission create a package-info.java class for Vert.x API code generation

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a package-info.java class in the io.serratus.api package. 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## Register the io.serratus.api package for the Vert.x API code generation plugin to find the API classes to generate event bus code for. 

Create a new file: /usr/local/src/serratus-api/src/main/java/io/serratus/api/package-info.java

```plain
// Register the io.serratus.api package for the Vert.x API code generation plugin to find the API classes to generate event bus code for. 
@ModuleGen(name="serratus-api", groupPackage="io.serratus.api")
package io.serratus.api;

```

## Import the Vert.x code generation module package. 

```plain

// Import the Vert.x code generation module package. 
import io.vertx.codegen.annotations.ModuleGen;

```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by manaswinidas** [comment]
Pull request link: https://github.com/team19hackathon2021/serratus-api/pull/11
