### ISSUE TITLE
to create a new Java class to organize base page data to be accessible in the Handlebars templating UI. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#46]
# Mission to create a new Java class to organize base page data to be accessible in the Handlebars templating UI. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java class to organize base page data to be accessible in the Handlebars templating UI. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.page
- **The Java class name will be:** PageLayout
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/page/PageLayout.java
- **The Java class will extend:** PageLayoutGen\<Object\>

```java
package io.serratus.api.enus.page;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.apache.commons.lang3.StringUtils;
import io.serratus.api.enus.config.ConfigKeys;
import io.serratus.api.enus.request.SiteRequestEnUS;
import io.serratus.api.enus.wrap.Wrap;
import io.vertx.core.Promise;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.api.service.ServiceRequest;

/**
 **/

public class PageLayout extends PageLayoutGen<Object> {
}
```

## Create the init method for the siteRequest_ field inside the PageLayout class

Create an initialization method that starts with an underscore (_)siteRequest_ to define the  siteRequest_ field

Here is a suggestion on what the code might look like: 

```java
	protected void _siteRequest_(Wrap<SiteRequestEnUS> w) {
	}
```

## Create the init method for the serviceRequest field inside the PageLayout class

Create an initialization method that starts with an underscore (_)serviceRequest to define the  serviceRequest field

Here is a suggestion on what the code might look like: 

```java
	protected void _serviceRequest(Wrap<ServiceRequest> w) {
		w.o(siteRequest_.getServiceRequest());
	}
```

## Create the init method for the requestZoneId field inside the PageLayout class

Create an initialization method that starts with an underscore (_)requestZoneId to define the  requestZoneId field

Here is a suggestion on what the code might look like: 

```java
	protected void _requestZoneId(Wrap<String> w) {
		w.o(Optional.ofNullable(siteRequest_.getRequestVars().get(VAR_requestZoneId)).orElse(siteRequest_.getConfig().getString(ConfigKeys.SITE_ZONE)));
	}
```

## Create the init method for the requestLocaleId field inside the PageLayout class

Create an initialization method that starts with an underscore (_)requestLocaleId to define the  requestLocaleId field

Here is a suggestion on what the code might look like: 

```java
	protected void _requestLocaleId(Wrap<String> w) {
		w.o(Optional.ofNullable(siteRequest_.getRequestHeaders().get("Accept-Language")).map(acceptLanguage -> StringUtils.substringBefore(acceptLanguage, ",")).orElse(siteRequest_.getConfig().getString(ConfigKeys.SITE_LOCALE)));
	}
```

## Create the init method for the staticBaseUrl field inside the PageLayout class

Create an initialization method that starts with an underscore (_)staticBaseUrl to define the  staticBaseUrl field

Here is a suggestion on what the code might look like: 

```java
	protected void _staticBaseUrl(Wrap<String> w) {
		w.o(siteRequest_.getConfig().getString(ConfigKeys.STATIC_BASE_URL));
	}
```

## Create the init method for the pageUri field inside the PageLayout class

Create an initialization method that starts with an underscore (_)pageUri to define the  pageUri field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageUri(Wrap<String> w) {
		w.o(serviceRequest.getExtra().getString("uri"));
	}
```

## Create the init method for the pageMethod field inside the PageLayout class

Create an initialization method that starts with an underscore (_)pageMethod to define the  pageMethod field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageMethod(Wrap<String> w) {
		w.o(serviceRequest.getExtra().getString("method"));
	}
```

## Create the init method for the params field inside the PageLayout class

Create an initialization method that starts with an underscore (_)params to define the  params field

Here is a suggestion on what the code might look like: 

```java
	protected void _params(Wrap<JsonObject> w) {
		w.o(serviceRequest.getParams());
	}
```

## Create the init method for the long0 field inside the PageLayout class

Create an initialization method that starts with an underscore (_)long0 to define the  long0 field

Here is a suggestion on what the code might look like: 

```java
	protected void _long0(Wrap<Long> w) {
		w.o(0L);
	}
```

## Create the init method for the long1 field inside the PageLayout class

Create an initialization method that starts with an underscore (_)long1 to define the  long1 field

Here is a suggestion on what the code might look like: 

```java
	protected void _long1(Wrap<Long> w) {
		w.o(1L);
	}
```

## Create the init method for the int0 field inside the PageLayout class

Create an initialization method that starts with an underscore (_)int0 to define the  int0 field

Here is a suggestion on what the code might look like: 

```java
	protected void _int0(Wrap<Integer> w) {
		w.o(0);
	}
```

## Create the init method for the int1 field inside the PageLayout class

Create an initialization method that starts with an underscore (_)int1 to define the  int1 field

Here is a suggestion on what the code might look like: 

```java
	protected void _int1(Wrap<Integer> w) {
		w.o(1);
	}
```

## Create the init method for the promiseBefore field inside the PageLayout class

Create an initialization method that starts with an underscore (_)promiseBefore to define the  promiseBefore field

Here is a suggestion on what the code might look like: 

```java
	protected void _promiseBefore(Wrap<Void> promise) {
		promise.complete();
	}
```

## Create the init method for the classSimpleName field inside the PageLayout class

Create an initialization method that starts with an underscore (_)classSimpleName to define the  classSimpleName field

Here is a suggestion on what the code might look like: 

```java
	protected void _classSimpleName(Wrap<String> c) {
	}
```

## Create the init method for the pageTitle field inside the PageLayout class

Create an initialization method that starts with an underscore (_)pageTitle to define the  pageTitle field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageTitle(Wrap<String> c) {
	}
```

## Create the init method for the roles field inside the PageLayout class

Create an initialization method that starts with an underscore (_)roles to define the  roles field

Here is a suggestion on what the code might look like: 

```java
protected void _roles(List<String> l) {
		if(siteRequest_ != null) {
			l.addAll(Stream.concat(siteRequest_.getUserResourceRoles().stream(), siteRequest_.getUserResourceRoles().stream()).collect(Collectors.toList()));
		}
	}
```

## Create the init method for the rolesRequired field inside the PageLayout class

Create an initialization method that starts with an underscore (_)rolesRequired to define the  rolesRequired field

Here is a suggestion on what the code might look like: 

```java
protected void _rolesRequired(List<String> l) {
		l.addAll(siteRequest_.getConfig().getJsonArray(ConfigKeys.AUTH_ROLES_ADMIN).stream().map(o -> o.toString()).collect(Collectors.toList()));
	}
```

## Create the init method for the authRolesAdmin field inside the PageLayout class

Create an initialization method that starts with an underscore (_)authRolesAdmin to define the  authRolesAdmin field

Here is a suggestion on what the code might look like: 

```java
protected void _authRolesAdmin(List<String> l) {
		l.addAll(siteRequest_.getConfig().getJsonArray(ConfigKeys.AUTH_ROLES_ADMIN).stream().map(o -> o.toString()).collect(Collectors.toList()));
	}
```

## Create the init method for the pagination field inside the PageLayout class

Create an initialization method that starts with an underscore (_)pagination to define the  pagination field

Here is a suggestion on what the code might look like: 

```java
protected void _pagination(JsonObject pagination) {
	}
```

## Create the init method for the query field inside the PageLayout class

Create an initialization method that starts with an underscore (_)query to define the  query field

Here is a suggestion on what the code might look like: 

```java
protected void _query(JsonObject query) {
	}
```

## Create the init method for the promiseAfter field inside the PageLayout class

Create an initialization method that starts with an underscore (_)promiseAfter to define the  promiseAfter field

Here is a suggestion on what the code might look like: 

```java
	protected void _promiseAfter(Wrap<Void> promise) {
		promise.complete();
	}
```

## Create the init method for the pageImageUri field inside the PageLayout class

Create an initialization method that starts with an underscore (_)pageImageUri to define the  pageImageUri field

Here is a suggestion on what the code might look like: 

```java
	protected void _pageImageUri(Wrap<String> c) {
	}
```

## Create the init method for the contextIconGroup field inside the PageLayout class

Create an initialization method that starts with an underscore (_)contextIconGroup to define the  contextIconGroup field

Here is a suggestion on what the code might look like: 

```java
	protected void _contextIconGroup(Wrap<String> c) {
	}
```

## Create the init method for the contextIconName field inside the PageLayout class

Create an initialization method that starts with an underscore (_)contextIconName to define the  contextIconName field

Here is a suggestion on what the code might look like: 

```java
	protected void _contextIconName(Wrap<String> c) {
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by rmuppane** [comment]
I am working on this
