### ISSUE TITLE
to create a new Java enum to handle date formatting in the frontend page requests

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#48]
# Mission to create a new Java enum to handle date formatting in the frontend page requests

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create a new Java enum to handle date formatting in the frontend page requests. 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.vertx
- **The Java class name will be:** DateHelpers
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/vertx/DateHelpers.java
- **The Java class will extend:** Enum

```java
package io.serratus.api.enus.vertx;

import java.io.IOException;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import com.github.jknack.handlebars.Helper;
import com.github.jknack.handlebars.Options;
import io.serratus.api.enus.java.ZonedDateTimeSerializer;

/**
 **/

public enum DateHelpers implements Helper<Object> {
}
```

## Create the formatZonedDateTime field inside the DateHelpers enum

```java
	formatZonedDateTime {
		@Override
		public CharSequence apply(final Object a, final Options options) throws IOException {
			String pattern = options.param(0);
			String localeId = options.param(1);
			Locale locale = Locale.forLanguageTag(localeId);
			String zone = options.param(2);
			ZoneId zoneId = ZoneId.of(zone);
			String str = (String)a;
			ZonedDateTime d = ZonedDateTime.parse(str, ZonedDateTimeSerializer.ZONED_DATE_TIME_FORMATTER);
			return DateTimeFormatter.ofPattern(pattern, locale).format(d.withZoneSameInstant(zoneId));
		}
	}
	;
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by pkesavap** [comment]
I accept
