### ISSUE TITLE
to create the a new Java backend class to override the generated methods to render the page for RNA sequence runs. 

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#50]
# Mission to create the a new Java backend class to override the generated methods to render the page for RNA sequence runs. 

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is to create the a new Java backend class to override the generated methods to render the page for RNA sequence runs. . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## The details of your mission: 

- **The Java package name will be:** io.serratus.api.enus.model.run
- **The Java class name will be:** SequenceRunPage
- **The path to the Java class will be:** /usr/local/src/serratus-api/src/main/java/io/serratus/api/enus/model/run/SequenceRunPage.java
- **The Java class will extend:** SequenceRunPageGen\<SequenceRunGenPage\>

```java
package io.serratus.api.enus.model.run;


/**
 **/

public class SequenceRunPage extends SequenceRunPageGen<SequenceRunGenPage> {
}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by jomarko** [comment]
taking this issue
