### ISSUE TITLE
create an application.properties file for defining the default config variable values

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-serratus#79]
# Mission create an application.properties file for defining the default config variable values

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Serratus")

Your mission, should you choose to accept it, is Create the file serratus-api/src/main/resources/application.properties. 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

An open science project to uncover the planetary virome, freely and openly

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/serratus-api/

## Define the JDBC Database properties. 

Create a new file: /usr/local/src/serratus-api/src/main/resources/application.properties

```plain
# Define the JDBC Database properties. 
JDBC_HOST=localhost
JDBC_PORT=5432
JDBC_DATABASE=serratus-api
JDBC_USERNAME=serratus-api
JDBC_PASSWORD=
JDBC_MAX_POOL_SIZE=10
JDBC_MAX_WAIT_QUEUE_SIZE=1000

# Define the site properties. 
SITE_HOST_NAME=localhost
SITE_PORT=11281
SITE_BASE_URL=http://localhost:11281
SITE_ZONE=America/Denver

```

## Define the Single-Sign On Authentication properties. 

```plain

# Define the Single-Sign On Authentication properties. 
AUTH_REALM=
AUTH_RESOURCE=
AUTH_SECRET=
AUTH_HOST_NAME=
AUTH_PORT=443
AUTH_SSL=true
AUTH_SSL_REQUIRED=all
AUTH_TOKEN_URI=/auth/realms/AUTH_REALM/protocol/openid-connect/token

```

## Define the Apache Zookeeper cluster manager properties. 

```plain

# Define the Apache Zookeeper cluster manager properties. 
ZOOKEEPER_HOST_NAME=localhost
ZOOKEEPER_PORT=2181

```

## Define the Apache Solr search engine properties. 

```plain

# Define the Apache Solr search engine properties. 
SOLR_URL=http://localhost:8983/solr/serratus-api
SOLR_HOST_NAME=localhost
SOLR_PORT=8983
SOLR_COLLECTION=serratus-api
SOLR_URL_COMPUTATE=http://localhost:8983/solr/computate

```

## Define the SMTP Email properties. 

```plain

# Define the SMTP Email properties. 
API_CONTACT_EMAIL=
EMAIL_HOST=
EMAIL_PORT=
EMAIL_SSL=
EMAIL_AUTH=
EMAIL_USERNAME=
EMAIL_PASSWORD=
EMAIL_FROM=
EMAIL_ADMIN=

```

## Define the static content properties. 

```plain

# Define the static content properties. 
STATIC_BASE_URL=http://localhost:11281/static
STATIC_PATH=/usr/local/src/serratus-api-static

```

## Define the API import properties. 

```plain

# Define the API import properties. 
API_COUNTER_PAUSE=10
API_COUNTER_RESUME=5

```

## Define the database to Solr sync properties, in case you restore the site from a database backup. 

```plain

# Define the database to Solr sync properties, in case you restore the site from a database backup. 
TIMER_DB_SOLR_SYNC_IN_SECONDS=1
ENABLE_DB_SOLR_SYNC=false
ENABLE_DB_SOLR_SYNC_TrafficContraband=true
ENABLE_DB_SOLR_SYNC_SearchBasis=true
ENABLE_DB_SOLR_SYNC_TrafficSearch=true
ENABLE_DB_SOLR_SYNC_TrafficPerson=true
ENABLE_DB_SOLR_SYNC_TrafficStop=true

```

## Enable the refresh data properties, in case you want to reindex the data in the search engine after doing more search engine tuning. 

```plain

# Enable the refresh data properties, in case you want to reindex the data in the search engine after doing more search engine tuning. 
ENABLE_REFRESH_DATA=false
ENABLE_REFRESH_DATA_TrafficContraband=true
ENABLE_REFRESH_DATA_SearchBasis=true
ENABLE_REFRESH_DATA_TrafficSearch=true
ENABLE_REFRESH_DATA_TrafficPerson=true
ENABLE_REFRESH_DATA_TrafficStop=true

```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by r00ta** [comment]
Can anybody assign this to me?

**Comment by r00ta** [comment]
Pull request opened https://github.com/team19hackathon2021/serratus-api/pull/3
